services:
  - type: web
    name: discord-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false  # Set manually in the dashboard
